In [1]:
import pandas as pd
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from sklearn import model_selection
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score


**membaca dataset dari URL,** Dataset yang digunakan adalah dataset Iris, yang berisi informasi tentang panjang dan lebar kelopak serta sepal (bagian bunga), dengan masing-masing data diklasifikasikan berdasarkan spesies bunga (Setosa, Versicolor, atau Virginica).

In [10]:
import pandas as pd

url = "http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv(url, names=names)


**Membuat daftar algoritma machine learning yang akan diuji atau dievaluasi.** Pertama, sebuah list kosong bernama models dibuat untuk menampung pasangan nama model dan objek modelnya. Selanjutnya, algoritma K-Nearest Neighbors (KNN) ditambahkan ke dalam list menggunakan fungsi append, dengan nama 'KNN' sebagai identitasnya dan KNeighborsClassifier() sebagai objek modelnya. Kemudian, algoritma Naive Bayes (NB) ditambahkan dengan nama 'NB' dan objek model GaussianNB(). Terakhir, algoritma Support Vector Machine (SVM) dimasukkan dengan nama 'SVM' dan objek model SVC().

In [11]:
# Spot Check Algorithms
models = []
models.append(('KNN', KNeighborsClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))

**Mengevaluasi performa setiap model dalam list models menggunakan cross-validation**  Untuk setiap model, hasil akurasi dihitung pada setiap fold, kemudian rata-rata akurasi dan deviasi standarnya dicetak. Hasil cross-validation disimpan ke dalam list results untuk analisis lebih lanjut, sementara nama model disimpan di list names. Evaluasi ini membantu membandingkan performa model secara konsisten pada data yang telah dibagi secara acak

In [12]:
# Evaluate each model in turn
results = []
names = []

for name, model in models:
    # Set shuffle=True to enable shuffling before splitting into folds
    kfold = model_selection.KFold(n_splits=10, random_state=seed, shuffle=True)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)


KNN: 0.983333 (0.033333)
NB: 0.966667 (0.040825)
SVM: 0.983333 (0.033333)


**model SVM** dengan data training, memprediksi data validasi, dan mengevaluasi performanya menggunakan akurasi, matriks kebingungan, dan laporan klasifikasi untuk memahami kualitas prediksi model.

In [13]:
# Make predictions on validation dataset
svm = SVC()
svm.fit(X_train, Y_train)
predictions = svm.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))


0.8666666666666667
[[ 7  0  0]
 [ 0 10  2]
 [ 0  2  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.83      0.83      0.83        12
 Iris-virginica       0.82      0.82      0.82        11

       accuracy                           0.87        30
      macro avg       0.88      0.88      0.88        30
   weighted avg       0.87      0.87      0.87        30



** model KNN,** melatih dan memprediksi data menggunakan SVM secara tidak konsisten. Model SVM dilatih pada data training dan memprediksi kelas data validasi. Hasil evaluasi performa meliputi akurasi, matriks kebingungan, dan laporan klasifikasi untuk memahami kemampuan model.

In [8]:
# Make predictions on validation dataset
KNN = KNeighborsClassifier()
svm.fit(X_train, Y_train)
predictions = svm.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.8666666666666667
[[ 7  0  0]
 [ 0 10  2]
 [ 0  2  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.83      0.83      0.83        12
 Iris-virginica       0.82      0.82      0.82        11

       accuracy                           0.87        30
      macro avg       0.88      0.88      0.88        30
   weighted avg       0.87      0.87      0.87        30



**model Naive Bayes (GaussianNB) **menggunakan data training (X_train, Y_train), kemudian memprediksi kelas data validasi (X_validation). Hasil prediksi dievaluasi dengan menghitung akurasi, menampilkan matriks kebingungan, dan laporan klasifikasi untuk melihat performa model.

In [9]:
nb = GaussianNB()
nb.fit(X_train, Y_train)
predictions = nb.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.8333333333333334
[[7 0 0]
 [0 9 3]
 [0 2 9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.82      0.75      0.78        12
 Iris-virginica       0.75      0.82      0.78        11

       accuracy                           0.83        30
      macro avg       0.86      0.86      0.86        30
   weighted avg       0.84      0.83      0.83        30



**KESIMPULAN :**
Dari ketiga model, SVM biasanya memiliki akurasi lebih tinggi pada dataset yang terpisah secara linear seperti Iris, berkat kemampuan mencari hyperplane optimal. KNN memberikan akurasi yang kompetitif, tetapi performanya dapat dipengaruhi oleh jumlah tetangga (k) dan distribusi data. Naive Bayes sering memiliki akurasi sedikit lebih rendah karena asumsi distribusi normalnya, tetapi tetap andal dan cepat untuk data sederhana. Evaluasi tambahan seperti matriks kebingungan dan laporan klasifikasi menunjukkan bahwa SVM sering lebih konsisten dalam mengklasifikasikan semua kelas.